export const details=[
    {
        firstname:"dinesh",
        lastname:"kumar",
        gender:"m",
        age:"21",
        state:"Tamilnadu",
        district:"madurai",
        symptoms:[
            {
                symptomsType:"fever",
                numberOfDays:"2"
            },
            {
                symptomsType:"pain",
                numberOfDays:"1"
            }
        ]
    },
    {
        firstname:"suresh",
        lastname:"kumar",
        gender:"m",
        age:"24",
        state:"Tamilnadu",
        district:"cheenai",
        symptoms:[
            {
                symptomsType:"pain",
                numberOfDays:"3"
            },
            {
                symptomsType:"headache",
                numberOfDays:"2"
            }
        ]
    }
]